load("@rules_cc//cc:cc_library.bzl", "cc_library")

licenses(["notice"])

cc_library(
    name = "common",
    hdrs = ["nearby_sharing_common.h"],
    visibility = ["//visibility:public"],
    deps = ["//proto:sharing_enums_cc_proto"],
)
